# Generated by Django 6.1 on 2026-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_apsis',
            field=models.BooleanField(default=True),
        ),
    ]
