# Generated by Django 6.1 on 2026-10-04 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apsis', '0002_post_has_apsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='svenska_kyrkan_place_id',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$')]),
        ),
    ]
