# Generated by Django 6.1 on 2026-08-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_milestone_task_milestone_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('done', 'Done')], default='not_started', max_length=20),
        ),
    ]
