# Generated by Django 6.1 on 2026-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='update',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
