# Generated by Django 6.1 on 2026-09-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_document_tag_milestone_tags_project_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flux.milestone'),
        ),
        migrations.AlterField(
            model_name='update',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='flux.milestone'),
        ),
        migrations.AlterField(
            model_name='update',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='flux.task'),
        ),
    ]
