# Generated by Django 6.1 on 2026-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0008_milestone_order_alter_task_milestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
