# Generated by Django 6.1 on 2026-09-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0009_alter_milestone_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('flowchart', 'Flowchart'), ('database_schema', 'Database schema'), ('decision', 'Decision')], default='markdown', max_length=20),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='flux.project')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('int', 'Integer'), ('bigint', 'Big integer'), ('decimal', 'Decimal'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'Date and time'), ('time', 'Time'), ('uuid', 'UUID'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('nullable', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='flux.entity')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('api', 'External API'), ('auth', 'Authentication'), ('storage', 'Storage'), ('email', 'Email'), ('payment', 'Payment'), ('other', 'Other')], default='api', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('env_vars', models.JSONField(blank=True, default=list, help_text='Names of required environment variables.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='flux.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fk', 'Foreign key'), ('m2m', 'Many to many'), ('o2o', 'One to one')], default='fk', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('related_name', models.CharField(blank=True, max_length=100)),
                ('on_delete', models.CharField(choices=[('cascade', 'Cascade'), ('protect', 'Protect'), ('set_null', 'Set null')], default='cascade', max_length=20)),
                ('nullable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='flux.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='flux.entity')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('operations', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=list, help_text='Field names usable as query filters.')),
                ('ordering', models.CharField(blank=True, max_length=100)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='flux.entity')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='flux.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('list', 'List'), ('retrieve', 'Retrieve'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('scope', models.CharField(choices=[('all', 'All'), ('own', 'Own'), ('member', 'Member')], default='all', max_length=20)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='flux.resource')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='flux.role')),
            ],
            options={
                'ordering': ['role', 'resource', 'operation'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entities', models.ManyToManyField(blank=True, related_name='screens', to='flux.entity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='flux.screen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='flux.project')),
            ],
            options={
                'ordering': ['route'],
            },
        ),
        migrations.CreateModel(
            name='SeedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_rows', to='flux.entity')),
            ],
            options={
                'ordering': ['entity', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StackProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.JSONField(blank=True, default=list, help_text='Any of: django, typescript, csharp.')),
                ('api_naming', models.CharField(choices=[('snake_case', 'snake_case'), ('camel_case', 'camelCase')], default='snake_case', max_length=20)),
                ('auth_method', models.CharField(choices=[('session', 'Session'), ('token', 'Token'), ('jwt', 'JWT'), ('none', 'None')], default='session', max_length=20)),
                ('database', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('sqlserver', 'SQL Server')], default='postgresql', max_length=20)),
                ('app_label', models.CharField(blank=True, help_text='Django app label for generated models.', max_length=100)),
                ('namespace', models.CharField(blank=True, help_text='C# root namespace.', max_length=200)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stack_profile', to='flux.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='flux_entity_unique_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='flux_field_unique_name_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='flux_integration_unique_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='flux_relation_unique_name_per_source'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='flux_role_unique_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'resource', 'operation'), name='flux_rolepermission_unique'),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('project', 'route'), name='flux_screen_unique_route_per_project'),
        ),
    ]
