# Generated by Django 6.1 on 2026-09-19 20:13

import django.db.models.deletion
import flux.models.identity
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0010_alter_document_kind_entity_field_integration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='include_identity',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VisualProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('tone', models.TextField(blank=True, help_text='Tone of voice for copy.')),
                ('colors', models.JSONField(blank=True, default=list, help_text='[{name, role, light, dark}] with #RRGGBB values.')),
                ('heading_font', models.CharField(blank=True, max_length=120)),
                ('body_font', models.CharField(blank=True, max_length=120)),
                ('mono_font', models.CharField(blank=True, max_length=120)),
                ('font_import_url', models.CharField(blank=True, help_text='Stylesheet that loads the fonts.', max_length=500)),
                ('font_weights', models.JSONField(blank=True, default=flux.models.identity.default_font_weights)),
                ('base_font_size', models.PositiveSmallIntegerField(default=16)),
                ('type_scale_ratio', models.DecimalField(decimal_places=3, default=Decimal('1.25'), max_digits=4)),
                ('spacing_unit', models.PositiveSmallIntegerField(default=4)),
                ('radii', models.JSONField(blank=True, default=flux.models.identity.default_radii)),
                ('shadows', models.JSONField(blank=True, default=dict)),
                ('assets', models.JSONField(blank=True, default=list, help_text='[{name, kind, url, usage}] logos, icons, favicons.')),
                ('logo_rules', models.TextField(blank=True, help_text='Minimum size, clear space, allowed backgrounds.')),
                ('icon_library', models.CharField(blank=True, max_length=60)),
                ('icon_style', models.CharField(blank=True, max_length=60)),
                ('accessibility_target', models.CharField(choices=[('AA', 'WCAG AA'), ('AAA', 'WCAG AAA')], default='AA', max_length=3)),
                ('guidelines', models.TextField(blank=True, help_text="Free-form markdown: imagery, do and don't, component rules.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='flux.visualprofile'),
        ),
        migrations.AddConstraint(
            model_name='visualprofile',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='flux_identity_unique_name_per_owner'),
        ),
    ]
