# Generated by Django 6.1 on 2026-09-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0011_project_include_identity_visualprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualprofile',
            name='default_mode',
            field=models.CharField(choices=[('system', 'Follow the system'), ('light', 'Light'), ('dark', 'Dark')], default='system', help_text='Which theme applies before the user chooses, when both exist.', max_length=6),
        ),
        migrations.AddField(
            model_name='visualprofile',
            name='shadows_dark',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides of shadows in dark mode.'),
        ),
        migrations.AddField(
            model_name='visualprofile',
            name='theme_modes',
            field=models.CharField(choices=[('light', 'Light only'), ('dark', 'Dark only'), ('both', 'Light and dark')], default='both', max_length=5),
        ),
        migrations.AlterField(
            model_name='visualprofile',
            name='assets',
            field=models.JSONField(blank=True, default=list, help_text='[{name, kind, mode (any/light/dark), url, usage}] logos, icons, favicons.'),
        ),
        migrations.AlterField(
            model_name='visualprofile',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='[{name, role, light, dark}] with #RRGGBB values; which values are required follows theme_modes.'),
        ),
    ]
