# Generated by Django 6.1 on 2026-09-20 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0012_visualprofile_default_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='integration',
            name='auth_env_var',
            field=models.CharField(blank=True, help_text='Env var with the key, token, username or client id.', max_length=100),
        ),
        migrations.AddField(
            model_name='integration',
            name='auth_name',
            field=models.CharField(blank=True, help_text='Header or query parameter carrying an API key.', max_length=100),
        ),
        migrations.AddField(
            model_name='integration',
            name='auth_secret_env_var',
            field=models.CharField(blank=True, help_text='Env var with the password or client secret.', max_length=100),
        ),
        migrations.AddField(
            model_name='integration',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('api_key_header', 'API key in a header'), ('api_key_query', 'API key in the query string'), ('bearer', 'Bearer token'), ('basic', 'HTTP basic'), ('oauth_client', 'OAuth client credentials')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='integration',
            name='base_url',
            field=models.CharField(blank=True, help_text='Base URL of an inbound data API (https).', max_length=300),
        ),
        migrations.AddField(
            model_name='integration',
            name='cache_ttl_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='Default cache time; 0 disables caching.'),
        ),
        migrations.AddField(
            model_name='integration',
            name='oauth_token_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='integration',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='retries',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='integration',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='IntegrationOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Python identifier used for the generated function.', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4)),
                ('path', models.CharField(help_text='Path relative to base_url; {param} marks path parameters.', max_length=300)),
                ('body_format', models.CharField(choices=[('json', 'JSON'), ('form', 'Form')], default='json', max_length=4)),
                ('params', models.JSONField(blank=True, default=list, help_text='[{name, in, type, required, default, description}]')),
                ('items_path', models.CharField(blank=True, help_text='Dotted path to the list in the response.', max_length=200)),
                ('pagination', models.CharField(choices=[('none', 'None'), ('offset', 'Offset and limit'), ('page', 'Page number'), ('cursor', 'Cursor')], default='none', max_length=6)),
                ('pagination_config', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=list, help_text='[{path, op, value}] applied to each item.')),
                ('key_field', models.CharField(blank=True, help_text='Entity field that identifies a record when syncing.', max_length=100)),
                ('mappings', models.JSONField(blank=True, default=list, help_text='[{path, field}] from an item to entity fields.')),
                ('sync', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_ttl_seconds', models.PositiveIntegerField(blank=True, help_text='Overrides the integration default.', null=True)),
                ('sample_response', models.JSONField(blank=True, help_text='A real response captured from the live API.', null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_operations', to='flux.entity')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='flux.integration')),
            ],
            options={
                'ordering': ['integration', 'name'],
                'constraints': [models.UniqueConstraint(fields=('integration', 'name'), name='flux_integrationoperation_unique_name')],
            },
        ),
    ]
