# Generated by Django 6.1 on 2026-09-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notification_domain'),
        ('flux', '0013_alter_project_options_integration_auth_env_var_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexIdempotencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_idempotency_requests', to='accounts.codextoken')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='flux_codexi_created_2ef2e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('token', 'key'), name='flux_codex_idempotency_token_key_unique')],
            },
        ),
    ]
