# Generated by Django 6.1 on 2026-09-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0014_codexidempotencyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(help_text='retrieve or a resource action path.', max_length=100)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('lifecycle', models.CharField(choices=[('derived', 'Derived'), ('embedded', 'Embedded'), ('transient', 'Transient')], default='derived', max_length=20)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_projections', to='flux.resource')),
                ('sources', models.ManyToManyField(blank=True, related_name='api_projections', to='flux.entity')),
            ],
            options={
                'ordering': ['resource', 'endpoint', 'name'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'endpoint', 'method', 'name'), name='flux_api_projection_unique_resource_endpoint_name')],
            },
        ),
    ]
