# Generated by Django 6.1 on 2026-09-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0015_apiprojection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order', 'created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='integrationoperation',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=6),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entities', models.ManyToManyField(blank=True, related_name='providers', to='flux.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='flux.project')),
                ('resources', models.ManyToManyField(blank=True, related_name='providers', to='flux.resource')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='flux_provider_unique_name_per_project')],
            },
        ),
    ]
