# Generated by Django 6.1 on 2026-09-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0016_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('list', 'List'), ('retrieve', 'Retrieve'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('custom', 'Custom')], max_length=20)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('request_schema', models.JSONField(blank=True, null=True)),
                ('pagination', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['resource', 'key', 'path'],
            },
        ),
        migrations.CreateModel(
            name='ApiOperationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['operation', 'status_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='apiprojection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'api_operation']},
        ),
        migrations.RemoveConstraint(
            model_name='apiprojection',
            name='flux_api_projection_unique_resource_endpoint_name',
        ),
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='flux_rolepermission_unique',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='ordering',
        ),
        migrations.AddField(
            model_name='apiprojection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_projections', to='flux.project'),
        ),
        migrations.AddField(
            model_name='apiprojection',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apiprojection',
            name='endpoint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apiprojection',
            name='lifecycle',
            field=models.CharField(default='derived', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiprojection',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_api_projections', to='flux.resource'),
        ),
        migrations.AlterField(
            model_name='apiprojection',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='legacy_api_projections', to='flux.entity'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='legacy_providers', to='flux.entity'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='operation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='apioperation',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_operations', to='flux.resource'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='api_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='flux.apioperation'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'api_operation'), name='flux_rolepermission_api_operation_unique'),
        ),
        migrations.AddField(
            model_name='apioperationresponse',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='flux.apioperation'),
        ),
        migrations.AddField(
            model_name='apioperationresponse',
            name='projection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_responses', to='flux.apiprojection'),
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='resource',
        ),
        migrations.AddConstraint(
            model_name='apioperation',
            constraint=models.UniqueConstraint(fields=('resource', 'key', 'method', 'path'), name='flux_api_operation_unique'),
        ),
        migrations.AddConstraint(
            model_name='apioperationresponse',
            constraint=models.UniqueConstraint(fields=('operation', 'status_code'), name='flux_api_operation_response_unique'),
        ),
    ]
