# Generated by Django 6.1 on 2026-09-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0017_apioperation_apioperationresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
    ]
