# Generated by Django 6.1 on 2026-08-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0002_venture_booking_bookingrequest_checkout_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='verso.house'),
        ),
        migrations.AddField(
            model_name='venture',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventures', to='verso.house'),
        ),
    ]
