# Generated by Django 6.1 on 2026-08-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0003_expense_house_venture_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='verso.venture')),
            ],
        ),
    ]
