# Generated by Django 6.1 on 2026-08-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0005_house_lat_house_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='verso.venture'),
        ),
    ]
