# Generated by Django 6.1 on 2026-08-25 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0007_update_author_update_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='VersoUpdate',
        ),
    ]
