# Generated by Django 6.1 on 2026-08-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0008_rename_update_versoupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='versoupdate',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='verso.house'),
        ),
    ]
