# Generated by Django 6.1 on 2026-08-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
