# Generated by Django 6.1 on 2026-09-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0012_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versoupdate',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
