# Generated by Django 6.1 on 2026-09-08 19:17

import django.contrib.postgres.fields
import verso.models.homes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0013_alter_versoupdate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=verso.models.homes.default_modules, null=True),
        ),
    ]
