# Generated by Django 6.1 on 2026-09-20 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0016_album_photo_album_cover_tag_photo_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='date_precision',
            field=models.CharField(choices=[('day', 'Exact day'), ('month', 'Month'), ('year', 'Year'), ('decade', 'Decade'), ('circa', 'Approximately')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='verso.house')),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('day', 'Exact day'), ('month', 'Month'), ('year', 'Year'), ('decade', 'Decade'), ('circa', 'Approximately')], default='year', max_length=10)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verso_history_events', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='verso.house')),
                ('photos', models.ManyToManyField(blank=True, related_name='history_events', to='verso.photo')),
                ('people', models.ManyToManyField(blank=True, related_name='events', to='verso.person')),
            ],
            options={
                'ordering': ['date_start', 'id'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='photos', to='verso.person'),
        ),
    ]
