# Generated by Django 6.1 on 2026-09-20 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0017_photo_credit_photo_date_precision_photo_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_year',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date_precision',
            field=models.CharField(choices=[('day', 'Exact day'), ('month', 'Month'), ('year', 'Year'), ('decade', 'Decade'), ('circa', 'Approximately')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_precision',
            field=models.CharField(choices=[('day', 'Exact day'), ('month', 'Month'), ('year', 'Year'), ('decade', 'Decade'), ('circa', 'Approximately')], default='day', max_length=10),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('day', 'Exact day'), ('month', 'Month'), ('year', 'Year'), ('decade', 'Decade'), ('circa', 'Approximately')], default='day', max_length=10)),
                ('source', models.TextField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verso_documents', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verso.house')),
                ('people', models.ManyToManyField(blank=True, related_name='documents', to='verso.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='verso.tag')),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='verso.venture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parent', 'Parent of'), ('spouse', 'Spouse of'), ('partner', 'Partner of'), ('sibling', 'Sibling of'), ('other', 'Other')], max_length=10)),
                ('start_year', models.SmallIntegerField(blank=True, null=True)),
                ('end_year', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='verso.house')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='verso.person')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='verso.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'related', 'kind'), name='verso_unique_person_relation'), models.CheckConstraint(condition=models.Q(('person', models.F('related')), _negated=True), name='verso_relation_not_self')],
            },
        ),
    ]
