# Generated by Django 6.1 on 2026-09-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verso', '0018_remove_person_birth_year_remove_person_death_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verso.photo'),
        ),
        migrations.AddField(
            model_name='personrelation',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
