# Generated by Django 6.1 on 2026-09-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation'),
        ('flux', '0007_document_tag_milestone_tags_project_tags_and_more'),
        ('verso', '0012_expense_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='invitation_exactly_one_target',
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('house__isnull', True), ('project__isnull', True), _connector='OR'), name='invitation_at_most_one_target'),
        ),
    ]
