# Generated by Django 6.1 on 2026-08-27 15:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenophase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('publisher', models.CharField(max_length=255)),
                ('accessed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dyntaxa_taxon_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('scientific_name', models.CharField(max_length=255)),
                ('swedish_name', models.CharField(blank=True, max_length=255)),
                ('taxon_rank', models.CharField(blank=True, max_length=50)),
                ('parent_dyntaxa_taxon_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('scientific_name',),
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempus_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tempus.checklist')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_items', to='tempus.species')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistSighting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='tempus.checklistitem')),
            ],
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('country', 'Land'), ('county', 'Län'), ('province', 'Landskap'), ('nature_reserve', 'Naturreservat'), ('biological_area', 'Biologiskt område')], max_length=30)),
                ('country_code', models.CharField(max_length=2)),
                ('geometry', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['kind', 'country_code'], name='tempus_geoa_kind_dbdc48_idx')],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='geo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='tempus.geoarea'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField()),
                ('location', models.JSONField(default=dict)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_items', models.ManyToManyField(blank=True, related_name='observations', through='tempus.ChecklistSighting', to='tempus.checklistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempus_observations', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='tempus.species')),
            ],
            options={
                'ordering': ('-observed_at',),
            },
        ),
        migrations.AddField(
            model_name='checklistsighting',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_sightings', to='tempus.observation'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('planned_date', models.DateField()),
                ('geometry', models.JSONField(default=dict)),
                ('corridor_metres', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempus_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('planned_date', 'name'),
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='tempus.route'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.JSONField(default=dict)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tempus.route')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='SeasonWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_day_of_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)])),
                ('peak_start_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)])),
                ('peak_end_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)])),
                ('end_day_of_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(366)])),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('geo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_windows', to='tempus.geoarea')),
                ('phenophase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_windows', to='tempus.phenophase')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_windows', to='tempus.source')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_windows', to='tempus.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('taxon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='species_category', to='tempus.species')),
            ],
            options={
                'verbose_name_plural': 'species categories',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='SpeciesCategoryMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tempus.speciescategory')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_memberships', to='tempus.species')),
            ],
        ),
        migrations.AddField(
            model_name='speciescategory',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='categories', through='tempus.SpeciesCategoryMembership', to='tempus.species'),
        ),
        migrations.CreateModel(
            name='SpeciesFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='tempus.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='checklistsighting',
            constraint=models.UniqueConstraint(fields=('checklist_item', 'observation'), name='tempus_unique_checklist_sighting'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='tempus_unique_route_stop_sequence'),
        ),
        migrations.AddIndex(
            model_name='seasonwindow',
            index=models.Index(fields=['species', 'phenophase', 'geo_area'], name='tempus_seas_species_fbfa48_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonwindow',
            index=models.Index(fields=['start_day_of_year', 'end_day_of_year'], name='tempus_seas_start_d_28acad_idx'),
        ),
        migrations.AddConstraint(
            model_name='seasonwindow',
            constraint=models.CheckConstraint(condition=models.Q(('start_day_of_year__range', (1, 366))), name='tempus_season_start_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='seasonwindow',
            constraint=models.CheckConstraint(condition=models.Q(('peak_start_day__isnull', True), ('peak_start_day__range', (1, 366)), _connector='OR'), name='tempus_peak_start_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='seasonwindow',
            constraint=models.CheckConstraint(condition=models.Q(('peak_end_day__isnull', True), ('peak_end_day__range', (1, 366)), _connector='OR'), name='tempus_peak_end_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='seasonwindow',
            constraint=models.CheckConstraint(condition=models.Q(('end_day_of_year__range', (1, 366))), name='tempus_season_end_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='seasonwindow',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), ('confidence__range', (0, 1)), _connector='OR'), name='tempus_confidence_between_zero_and_one'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['user', 'observed_at'], name='tempus_obse_user_id_9b8fab_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'species'), name='tempus_unique_checklist_species'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'sequence'), name='tempus_unique_checklist_item_sequence'),
        ),
        migrations.AddConstraint(
            model_name='speciescategorymembership',
            constraint=models.UniqueConstraint(fields=('category', 'species'), name='tempus_unique_species_category_membership'),
        ),
        migrations.AddConstraint(
            model_name='speciesfollow',
            constraint=models.UniqueConstraint(fields=('user', 'species'), name='tempus_unique_user_species_follow'),
        ),
    ]
