# Generated by Django 6.1 on 2026-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciescategory',
            name='taxon',
        ),
        migrations.AddField(
            model_name='speciescategory',
            name='taxon',
            field=models.ManyToManyField(related_name='species_category', to='tempus.species'),
        ),
    ]
