# Generated by Django 6.1 on 2026-08-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0002_remove_speciescategory_taxon_speciescategory_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescategory',
            name='taxon',
            field=models.ManyToManyField(blank=True, null=True, related_name='species_category', to='tempus.species'),
        ),
    ]
