# Generated by Django 6.1 on 2026-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0003_alter_speciescategory_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescategory',
            name='taxon',
            field=models.ManyToManyField(blank=True, related_name='species_category', to='tempus.species'),
        ),
    ]
