# Generated by Django 6.1 on 2026-08-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0004_alter_speciescategory_taxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescategory',
            name='taxon_id',
            field=models.PositiveBigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='speciescategory',
            name='label',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
