# Generated by Django 6.1 on 2026-08-28 11:00
#
# Hand-edited: the autodetector emitted AlterField for the through= removal on
# Observation.checklist_items / SpeciesCategory.species, which Django's schema
# editor rejects ("you cannot ... add or remove through= on M2M fields"). The
# field has to be dropped, the through model deleted, then a plain M2M re-added.
#
# NOTE: this drops tempus_checklistsighting and tempus_speciescategorymembership
# and creates fresh, empty join tables. Existing links are NOT carried over.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0005_speciescategory_taxon_id_alter_speciescategory_label'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistsighting',
            name='tempus_unique_checklist_sighting',
        ),
        migrations.RemoveConstraint(
            model_name='speciescategorymembership',
            name='tempus_unique_species_category_membership',
        ),
        # Drop the through-backed M2M fields first so the through models are
        # no longer referenced.
        migrations.RemoveField(
            model_name='observation',
            name='checklist_items',
        ),
        migrations.RemoveField(
            model_name='speciescategory',
            name='species',
        ),
        # Now the join models are ordinary two-FK models and can be deleted.
        migrations.RemoveField(
            model_name='checklistsighting',
            name='checklist_item',
        ),
        migrations.RemoveField(
            model_name='checklistsighting',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='speciescategorymembership',
            name='category',
        ),
        migrations.RemoveField(
            model_name='speciescategorymembership',
            name='species',
        ),
        migrations.DeleteModel(
            name='ChecklistSighting',
        ),
        migrations.DeleteModel(
            name='SpeciesCategoryMembership',
        ),
        # Re-add as plain many-to-many (Django manages the join tables).
        migrations.AddField(
            model_name='observation',
            name='checklist_items',
            field=models.ManyToManyField(blank=True, related_name='observations', to='tempus.checklistitem'),
        ),
        migrations.AddField(
            model_name='speciescategory',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tempus.species'),
        ),
    ]
