# Generated by Django 6.1 on 2026-08-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0008_species_landscape_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seasonwindow',
            name='tempus_seas_species_fbfa48_idx',
        ),
        migrations.RemoveIndex(
            model_name='seasonwindow',
            name='tempus_seas_start_d_28acad_idx',
        ),
        migrations.RemoveConstraint(
            model_name='seasonwindow',
            name='tempus_season_start_valid_day',
        ),
        migrations.RemoveConstraint(
            model_name='seasonwindow',
            name='tempus_peak_start_valid_day',
        ),
        migrations.RemoveConstraint(
            model_name='seasonwindow',
            name='tempus_peak_end_valid_day',
        ),
        migrations.RemoveConstraint(
            model_name='seasonwindow',
            name='tempus_season_end_valid_day',
        ),
        migrations.RemoveConstraint(
            model_name='seasonwindow',
            name='tempus_confidence_between_zero_and_one',
        ),
        migrations.DeleteModel(
            name='SeasonWindow',
        ),
    ]
