# Generated by Django 6.1 on 2026-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0009_remove_seasonwindow_tempus_seas_species_fbfa48_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='biotopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
