# Generated by Django 6.1 on 2026-08-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0010_species_biotopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
