# Generated by Django 6.1 on 2026-08-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0011_checklist_end_date_checklist_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='planned_date',
        ),
    ]
