# Generated by Django 6.1 on 2026-08-30 01:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0012_remove_checklist_planned_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdnetDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('detected_at', models.DateTimeField()),
                ('device_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdnet_detections', to='tempus.species')),
            ],
            options={
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['-detected_at'], name='tempus_bird_detecte_9b71af_idx'), models.Index(fields=['device_id', '-detected_at'], name='tempus_bird_device__30ca8d_idx')],
            },
        ),
    ]
