# Generated by Django 6.1 on 2026-08-30 03:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0013_birdnetdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenogram',
            name='significance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='phenogram',
            name='significance_basis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='species',
            name='significance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='RouteSuggestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_run', to='tempus.route')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
