# Generated by Django 6.1 on 2026-08-30 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0014_phenogram_significance_phenogram_significance_basis_and_more'),
        ('verso', '0012_expense_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdnetDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'identifier'),
            },
        ),
        migrations.AddField(
            model_name='birdnetdevice',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birdnet_devices', to='verso.house'),
        ),
        migrations.AddField(
            model_name='birdnetdevice',
            name='users',
            field=models.ManyToManyField(related_name='birdnet_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveIndex(
            model_name='birdnetdetection',
            name='tempus_bird_device__30ca8d_idx',
        ),
        migrations.RemoveField(
            model_name='birdnetdetection',
            name='device_id',
        ),
        migrations.AddField(
            model_name='birdnetdetection',
            name='device',
            field=models.ForeignKey(db_column='device_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tempus.birdnetdevice'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='birdnetdetection',
            index=models.Index(fields=['device', '-detected_at'], name='tempus_bird_birdnet_b5efe3_idx'),
        ),
    ]
