# Generated by Django 6.1 on 2026-08-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0015_birdnetdevice_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='birdnetdetection',
            name='tempus_bird_birdnet_b5efe3_idx',
        ),
        migrations.RemoveField(
            model_name='birdnetdetection',
            name='device',
        ),
    ]
