# Generated by Django 6.1 on 2026-08-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0016_remove_birdnetdetection_tempus_bird_birdnet_b5efe3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdnetdetection',
            name='device',
            field=models.ForeignKey(db_column='device_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tempus.birdnetdevice'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='birdnetdetection',
            index=models.Index(fields=['device', '-detected_at'], name='tempus_bird_device__30ca8d_idx'),
        ),
    ]
