# Generated by Django 6.1 on 2026-08-30

import uuid

from django.db import migrations, models


def copy_existing_memberships(apps, schema_editor):
    SpeciesCategory = apps.get_model("tempus", "SpeciesCategory")
    SpeciesCategoryMembership = apps.get_model("tempus", "SpeciesCategoryMembership")

    for category in SpeciesCategory.objects.prefetch_related("species").all():
        for species in category.species.all():
            SpeciesCategoryMembership.objects.get_or_create(
                category_id=category.pk,
                species_id=species.pk,
                defaults={"is_primary": False},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("tempus", "0017_birdnetdetection_device_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesCategoryMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="memberships",
                        to="tempus.speciescategory",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="category_memberships",
                        to="tempus.species",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="speciescategorymembership",
            constraint=models.UniqueConstraint(
                fields=("category", "species"),
                name="tempus_unique_species_category_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="speciescategorymembership",
            constraint=models.UniqueConstraint(
                fields=("species",),
                condition=models.Q(is_primary=True),
                name="tempus_unique_primary_species_category",
            ),
        ),
        migrations.RunPython(copy_existing_memberships, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="speciescategory",
                    name="species",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="categories",
                        through="tempus.SpeciesCategoryMembership",
                        through_fields=("category", "species"),
                        to="tempus.species",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
