# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tempus", "0018_speciescategorymembership_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciescategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="children",
                to="tempus.speciescategory",
            ),
        ),
    ]
