# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


def copy_primary_memberships_to_categories(apps, schema_editor):
    SpeciesCategory = apps.get_model("tempus", "SpeciesCategory")
    SpeciesCategoryMembership = apps.get_model("tempus", "SpeciesCategoryMembership")

    primary_category_ids = (
        SpeciesCategoryMembership.objects.filter(is_primary=True)
        .values_list("category_id", flat=True)
        .distinct()
    )
    SpeciesCategory.objects.filter(pk__in=primary_category_ids).update(is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tempus", "0019_speciescategory_parent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciescategory",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_primary_memberships_to_categories, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="speciescategorymembership",
            name="tempus_unique_primary_species_category",
        ),
        migrations.RemoveField(
            model_name="speciescategorymembership",
            name="is_primary",
        ),
    ]
