# Generated by Django 6.1 on 2026-08-31 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0020_speciescategory_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenogramGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('years', models.PositiveSmallIntegerField(default=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geo_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenogram_generations', to='tempus.geoarea')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenogram_generations', to='tempus.species')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('geo_area__isnull', False)), fields=('species', 'geo_area'), name='tempus_unique_phenogram_generation_area'), models.UniqueConstraint(condition=models.Q(('geo_area__isnull', True)), fields=('species',), name='tempus_unique_phenogram_generation_range')],
            },
        ),
    ]
