# Generated by Django 6.1 on 2026-09-04 17:25

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tempus", "0021_phenogramgeneration"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="species",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    "swedish_name", name="gin_trgm_ops"
                ),
                name="tempus_species_swe_trgm_idx",
            ),
        ),
    ]
