# Generated by Django 6.1 on 2026-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0022_species_tempus_species_swe_trgm_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='auto_add',
            field=models.BooleanField(default=True),
        ),
    ]
