# Generated by Django 6.1 on 2026-09-04 19:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0023_checklist_auto_add'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='species',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['dyntaxa_taxon_id', 'parent_dyntaxa_taxon_id'], name='tempus_spec_dyntaxa_15d752_btree'),
        ),
    ]
