# Generated by Django 6.1 on 2026-09-06 17:05

import django.contrib.postgres.fields
import tempus.models.species
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0024_species_tempus_spec_dyntaxa_15d752_btree'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescategory',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=tempus.models.species.default_species_category_stages),
        ),
    ]
