# Generated by Django 6.1 on 2026-09-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0025_speciescategory_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='life_stage',
            field=models.TextField(null=True),
        ),
    ]
