# Generated by Django 6.1 on 2026-09-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0027_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='checklists',
        ),
        migrations.AddField(
            model_name='checklist',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tempus.locale'),
        ),
        migrations.AddField(
            model_name='observation',
            name='locale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tempus.locale'),
        ),
    ]
