# Generated by Django 6.1 on 2026-09-17 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0028_remove_locale_checklists_checklist_locale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandCoverFetch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('buffer_metres', models.PositiveIntegerField(default=5000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('locale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_cover_fetch', to='tempus.locale')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
