# Generated by Django 6.1 on 2026-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0029_landcoverfetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='landcoverfetch',
            name='hydrography',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
