# Generated by Django 6.1 on 2026-09-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0030_landcoverfetch_hydrography'),
    ]

    operations = [
        migrations.AddField(
            model_name='landcoverfetch',
            name='place_names',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
