# Generated by Django 6.1 on 2026-09-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0031_landcoverfetch_place_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='landcoverfetch',
            name='buildings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
