# Generated by Django 6.1 on 2026-09-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempus', '0032_landcoverfetch_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='landcoverfetch',
            name='roads',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
