"""
Django settings for origo project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file (repo root) into os.environ if present. Real values
# in the environment always take precedence, so deployed environments that set
# variables directly are unaffected. See .env.example for the supported keys.
try:
    from dotenv import load_dotenv
except ImportError:
    pass
else:
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Debugging and secrets must always be configured explicitly. Failing fast is
# safer than accidentally starting a production process with a known key.
DEBUG = os.environ.get("DEBUG", "False").strip().lower() == "true"
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY must be set.")

# ---------------------------------------------------------------------------
# Domains
# ---------------------------------------------------------------------------
# The whole host/CORS/CSRF configuration below is derived from this single
# list. To bring a new domain online, just add it to the DOMAINS env var
# (comma-separated) - nothing else in this file needs to change:
#
#     DOMAINS=origo.test,xn--fvitsko-exa.se,example.com
#
# Each domain is expected to serve:
#   - the API at   <API_SUBDOMAIN>.<domain>
#   - a frontend at <sub>.<domain>   for every sub in FRONTEND_SUBDOMAINS
#
# Punycode (xn--...) domains work here as-is; use the encoded form.

DOMAINS = [
    d.strip() for d in os.environ.get("DOMAINS", "origo.test").split(",") if d.strip()
]

FRONTEND_SUBDOMAINS = [
    s.strip()
    for s in os.environ.get("FRONTEND_SUBDOMAINS", "flux,verso,apsis").split(",")
    if s.strip()
]

API_SUBDOMAIN = os.environ.get("API_SUBDOMAIN", "origo.api")

# Ports the Next.js frontends run on in local development (for CSRF only).
FRONTEND_DEV_PORTS = [
    p.strip()
    for p in os.environ.get("FRONTEND_DEV_PORTS", "3000").split(",")
    if p.strip()
]


def _frontend_origins(schemes=("https",), ports=(None,)):
    """Build <scheme>://<sub>.<domain>[:port] for every frontend subdomain."""
    origins = []
    for domain in DOMAINS:
        for sub in FRONTEND_SUBDOMAINS:
            for scheme in schemes:
                for port in ports:
                    host = f"{sub}.{domain}"
                    origins.append(
                        f"{scheme}://{host}:{port}" if port else f"{scheme}://{host}"
                    )
    return origins


# An explicit ALLOWED_HOSTS env var still wins; otherwise allow every domain
# and all of its subdomains.
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS = [
        h.strip() for h in os.environ["ALLOWED_HOSTS"].split(",") if h.strip()
    ]
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    for domain in DOMAINS:
        ALLOWED_HOSTS += [domain, f".{domain}"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "django_tasks",
    "django_tasks_db",
    "corsheaders",
    "accounts",
    "flux",
    "opus",
    "verso",
    "apsis",
    "tempus",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTH_USER_MODEL = "accounts.User"

ROOT_URLCONF = "origo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "origo" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "origo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# DATABASE_URL unset -> local SQLite. A PostgreSQL URL is parsed with the
# standard library so database configuration has no third-party dependency.

database_url = os.environ.get("DATABASE_URL")

if database_url:
    parsed_database_url = urlparse(database_url)
    if parsed_database_url.scheme not in ("postgres", "postgresql"):
        raise ValueError("DATABASE_URL must use the postgres or postgresql scheme.")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed_database_url.path.lstrip("/")),
            "USER": unquote(parsed_database_url.username or ""),
            "PASSWORD": unquote(parsed_database_url.password or ""),
            "HOST": parsed_database_url.hostname or "",
            "PORT": parsed_database_url.port or "",
            # The threaded Django development server creates a new request
            # thread frequently; retaining a connection for ten minutes per
            # thread can exhaust a small remote PostgreSQL instance even for
            # one user. Keep local connections request-scoped, while allowing
            # production to opt into a bounded lifetime.
            "CONN_MAX_AGE": int(
                os.environ.get("DB_CONN_MAX_AGE", "0" if DEBUG else "60")
            ),
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": dict(parse_qsl(parsed_database_url.query)),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
redis_url = os.environ.get("REDIS_URL")

if redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": redis_url,
            "KEY_PREFIX": "origo",
            "TIMEOUT": 300,
        }
    }
else:
    # DatabaseCache, not LocMemCache: the marktäcke/land-cover map cache is
    # meant to be genuinely persistent (30-day TTL, see
    # LANTMATERIET_MARKTACKE's MAP_CACHE_SECONDS above) — LocMemCache lives
    # only in a single worker process's RAM and is gone on every restart or
    # deploy, and is not shared between worker processes either. No Redis
    # here by choice; DatabaseCache uses the existing database instead of an
    # extra service. Requires the cache table to exist
    # (`manage.py createcachetable`, run once, outside this settings file).
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_cache",
            "OPTIONS": {
                "MAX_ENTRIES": 10000,
                "CULL_FREQUENCY": 4,
            },
        }
    }
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email (Resend)
# Keys are supplied only by the deployment environment, never committed here.
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", "")

APSIS_NEWSLETTER_TIME_ZONE = os.environ.get(
    "APSIS_NEWSLETTER_TIME_ZONE", "Europe/Stockholm"
)


# Web Push (VAPID)
# One key pair, generated once (`vapid --gen` / `npx web-push generate-vapid-keys`).
# The public key must also be handed to the frontend as NEXT_PUBLIC_VAPID_PUBLIC_KEY.
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_SUBJECT = os.environ.get(
    "WEBPUSH_VAPID_SUBJECT", "mailto:frida.merell@gmail.com"
)


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "push-subscriptions": "30/min",
        "push-test": "6/min",
    },
}


# Background tasks (django-tasks / DEP 0014)
# Phenogram generation runs off the request cycle. The database backend
# (django-tasks-db) needs a worker process: `python manage.py db_worker`. Set
# TASKS_BACKEND to `django_tasks.backends.immediate.ImmediateBackend` to run
# tasks inline (dev, or a deploy with no worker); tests force the immediate
# backend.

TASKS = {
    "default": {
        "BACKEND": os.environ.get(
            "TASKS_BACKEND",
            "django_tasks_db.DatabaseBackend",
        ),
    }
}


# Cross-subdomain session cookie
# The Next.js frontends live on separate subdomains of a shared root domain
# and need to share the Django session cookie. A cookie can only be scoped to
# one root domain, so the session/CSRF cookies use ROOT_DOMAIN, which defaults
# to the first entry in DOMAINS. Override via the ROOT_DOMAIN env var if the
# primary domain is not listed first.

ROOT_DOMAIN = os.environ.get("ROOT_DOMAIN", DOMAINS[0])

SESSION_COOKIE_DOMAIN = f".{ROOT_DOMAIN}"
CSRF_COOKIE_DOMAIN = f".{ROOT_DOMAIN}"


# CORS
# https://github.com/adamchainz/django-cors-headers
# Allows the separately-hosted Next.js frontends to call this API with
# credentials (the session cookie) attached. Every origin must be explicitly
# named: a wildcard would allow any controlled or accidentally taken-over
# subdomain to make authenticated cross-origin requests.


def _explicit_origins(name):
    origins = [
        origin.strip()
        for origin in os.environ.get(name, "").split(",")
        if origin.strip()
    ]
    if any("*" in origin for origin in origins):
        raise ImproperlyConfigured(f"{name} must not contain wildcard origins.")
    return origins


DEFAULT_FRONTEND_ORIGINS = _frontend_origins(schemes=("https",)) + [
    f"https://{domain}" for domain in DOMAINS
]
if DEBUG:
    DEFAULT_FRONTEND_ORIGINS += _frontend_origins(
        schemes=("http", "https"),
        ports=FRONTEND_DEV_PORTS,
    )
    # A frontend served straight from the root domain (e.g. the dev chat on
    # http://origo.test:3000) rather than a <sub>.<domain> host.
    DEFAULT_FRONTEND_ORIGINS += [
        f"{scheme}://{domain}:{port}"
        for domain in DOMAINS
        for scheme in ("http", "https")
        for port in FRONTEND_DEV_PORTS
    ]

CORS_ALLOWED_ORIGINS = (
    _explicit_origins("CORS_ALLOWED_ORIGINS") or DEFAULT_FRONTEND_ORIGINS
)

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = _explicit_origins("CSRF_TRUSTED_ORIGINS") or CORS_ALLOWED_ORIGINS


# ---------------------------------------------------------------------------
# SLU Artdatabanken APIs (used by the tempus app)
# ---------------------------------------------------------------------------
# Species observations, Dyntaxa taxonomy and Artfakta species information, all
# behind one API gateway at api.artdatabanken.se. Each product has its own
# subscription key, issued on the developer portal (api-portal.artdatabanken.se).
# Calls are no-ops until the relevant *_KEY variable is set; see
# tempus/services/artdatabanken.py and .claude/skills/artdatabanken-api/.

ARTDATABANKEN = {
    "SPECIES_OBSERVATION_URL": os.environ.get(
        "ARTDATABANKEN_SPECIES_OBSERVATION_URL",
        "https://api.artdatabanken.se/species-observation-system/v1",
    ),
    "TAXON_SERVICE_URL": os.environ.get(
        "ARTDATABANKEN_TAXON_SERVICE_URL",
        "https://api.artdatabanken.se/taxonservice/v1",
    ),
    "SPECIES_INFORMATION_URL": os.environ.get(
        "ARTDATABANKEN_SPECIES_INFORMATION_URL",
        "https://api.artdatabanken.se/information/v1",
    ),
    "SUBSCRIPTION_KEY_SOS": os.environ.get("ARTDATABANKEN_SUBSCRIPTION_KEY_SOS"),
    "SUBSCRIPTION_KEY_TAXON": os.environ.get("ARTDATABANKEN_SUBSCRIPTION_KEY_TAXON"),
    "SUBSCRIPTION_KEY_SPECIES_INFORMATION": os.environ.get(
        "ARTDATABANKEN_SUBSCRIPTION_KEY_SPECIES_INFORMATION"
    ),
    "TIMEOUT": float(os.environ.get("ARTDATABANKEN_TIMEOUT", "30")),
    # SOS observation pages used to build phenograms are substantially larger
    # than taxonomy metadata responses and need a separate socket timeout.
    "PHENOGRAM_TIMEOUT": float(os.environ.get("ARTDATABANKEN_PHENOGRAM_TIMEOUT", "60")),
    # Minimum quiet period after any Artdatabanken response before another
    # Dyntaxa, Artfakta or SOS request may start. Shared across local processes.
    "COOLDOWN_SECONDS": float(os.environ.get("ARTDATABANKEN_COOLDOWN_SECONDS", "1")),
    "COOLDOWN_STATE_FILE": os.environ.get("ARTDATABANKEN_COOLDOWN_STATE_FILE"),
    "USER_AGENT": os.environ.get(
        "ARTDATABANKEN_USER_AGENT", "Tempus (+tempus.services.artdatabanken)"
    ),
    # Artfakta SpeciesDataService dataset path segments. The biotoper segment is
    # unverified; override if biotopes come back empty (see BIOTOPES_DATASET in
    # tempus/services/artdatabanken.py).
    "SPECIESDATA_LANDSCAPES_PATH": os.environ.get(
        "ARTDATABANKEN_SPECIESDATA_LANDSCAPES_PATH", "landscapetypes"
    ),
    "SPECIESDATA_BIOTOPES_PATH": os.environ.get(
        "ARTDATABANKEN_SPECIESDATA_BIOTOPES_PATH", "biotopes"
    ),
}


# ---------------------------------------------------------------------------
# Lantmäteriet Marktäcke Direkt (OGC API Features)
# ---------------------------------------------------------------------------
# The API is selected instead of the STAC download service because Locales use
# point lookups. Collections are discovered from the authenticated service;
# COLLECTION_IDS is only an optional allow-list for selected subsets.
LANTMATERIET_MARKTACKE = {
    "BASE_URL": os.environ.get(
        "LANTMATERIET_MARKTACKE_BASE_URL",
        "https://api.lantmateriet.se/ogc-features/v1/marktacke",
    ),
    "COLLECTION_IDS": tuple(
        value.strip()
        for value in os.environ.get("LANTMATERIET_MARKTACKE_COLLECTION_IDS", "").split(",")
        if value.strip()
    ),
    # Prefer a manually obtained API Portal access token when one is
    # available. Private Geotorget customers instead use Basic authentication
    # below - confirmed sufficient on its own by Lantmäteriet's documentation,
    # not just a fallback (see _authorization_header in lantmateriet.py).
    "ACCESS_TOKEN": os.environ.get("LANTMATERIET_MARKTACKE_ACCESS_TOKEN"),
    "USERNAME": os.environ.get("LANTMATERIET_MARKTACKE_USERNAME"),
    "PASSWORD": os.environ.get("LANTMATERIET_MARKTACKE_PASSWORD"),
    "TIMEOUT": float(os.environ.get("LANTMATERIET_MARKTACKE_TIMEOUT", "15")),
    "MAP_CACHE_SECONDS": int(
        os.environ.get("LANTMATERIET_MARKTACKE_MAP_CACHE_SECONDS", str(60 * 60 * 24 * 30))
    ),
    "MAP_PAGE_SIZE": int(os.environ.get("LANTMATERIET_MARKTACKE_MAP_PAGE_SIZE", "1000")),
    "MAP_MAX_FEATURES": int(os.environ.get("LANTMATERIET_MARKTACKE_MAP_MAX_FEATURES", "10000")),
}

# Kommun, Län och Rike Direkt is an OGC API Features service. It uses the same
# Geotorget credentials as Marktäcke.
LANTMATERIET_ADMINISTRATIVE_BOUNDARIES = {
    "BASE_URL": os.environ.get(
        "LANTMATERIET_ADMINISTRATIVE_BOUNDARIES_BASE_URL",
        "https://api.lantmateriet.se/ogc-features/v1/administrativ-indelning",
    ),
    "COLLECTION_IDS": tuple(
        value.strip()
        for value in os.environ.get(
            "LANTMATERIET_ADMINISTRATIVE_BOUNDARIES_COLLECTION_IDS", ""
        ).split(",")
        if value.strip()
    ),
    "TIMEOUT": float(os.environ.get("LANTMATERIET_ADMINISTRATIVE_BOUNDARIES_TIMEOUT", "15")),
    "MAP_CACHE_SECONDS": int(
        os.environ.get(
            "LANTMATERIET_ADMINISTRATIVE_BOUNDARIES_MAP_CACHE_SECONDS", str(60 * 60 * 24 * 30)
        )
    ),
    "MAP_PAGE_SIZE": int(
        os.environ.get("LANTMATERIET_ADMINISTRATIVE_BOUNDARIES_MAP_PAGE_SIZE", "1000")
    ),
    "MAP_MAX_FEATURES": int(
        os.environ.get("LANTMATERIET_ADMINISTRATIVE_BOUNDARIES_MAP_MAX_FEATURES", "10000")
    ),
}

# Hydrografi is a separate Lantmäteriet OGC API Features product from
# Marktäcke (lakes, watercourses, and the land-water boundary/coastline; sea
# surface itself is not its own collection here - it already comes from
# Marktäcke's "markytor" "Hav" objekttyp). Uses the same Geotorget credentials
# as Marktäcke, like LANTMATERIET_ADMINISTRATIVE_BOUNDARIES above.
LANTMATERIET_HYDROGRAFI = {
    "BASE_URL": os.environ.get(
        "LANTMATERIET_HYDROGRAFI_BASE_URL",
        "https://api.lantmateriet.se/ogc-features/v1/hydrografi",
    ),
    "COLLECTION_IDS": tuple(
        value.strip()
        for value in os.environ.get("LANTMATERIET_HYDROGRAFI_COLLECTION_IDS", "").split(",")
        if value.strip()
    ),
    "TIMEOUT": float(os.environ.get("LANTMATERIET_HYDROGRAFI_TIMEOUT", "15")),
    "MAP_CACHE_SECONDS": int(
        os.environ.get("LANTMATERIET_HYDROGRAFI_MAP_CACHE_SECONDS", str(60 * 60 * 24 * 30))
    ),
    "MAP_PAGE_SIZE": int(os.environ.get("LANTMATERIET_HYDROGRAFI_MAP_PAGE_SIZE", "1000")),
    "MAP_MAX_FEATURES": int(os.environ.get("LANTMATERIET_HYDROGRAFI_MAP_MAX_FEATURES", "10000")),
}

# Ortnamn Direkt (place names) is a separate Lantmäteriet REST API, not OGC
# API Features like the three products above - its base path is
# "distribution/produkter/ortnamn/v2.2", not "ogc-features/v1/...". v2.2 is the
# current version; the previous v2.1 is outgoing and answers 401 to accounts
# authorized for the current one. It has no bbox/radius search; only
# name/point/kommun/län criteria - see tempus/services/lantmateriet.py's
# Ortnamn section for what that means for the Locale endpoints. Falls back to
# the Marktäcke credentials above unless its own USERNAME/PASSWORD/
# ACCESS_TOKEN are set - confirmed live that the shared Basic credentials are
# accepted on v2.2.
LANTMATERIET_ORTNAMN = {
    "BASE_URL": os.environ.get(
        "LANTMATERIET_ORTNAMN_BASE_URL",
        "https://api.lantmateriet.se/distribution/produkter/ortnamn/v2.2",
    ),
    "ACCESS_TOKEN": os.environ.get(
        "LANTMATERIET_ORTNAMN_ACCESS_TOKEN",
        os.environ.get("LANTMATERIET_MARKTACKE_ACCESS_TOKEN"),
    ),
    "USERNAME": os.environ.get(
        "LANTMATERIET_ORTNAMN_USERNAME", os.environ.get("LANTMATERIET_MARKTACKE_USERNAME")
    ),
    "PASSWORD": os.environ.get(
        "LANTMATERIET_ORTNAMN_PASSWORD", os.environ.get("LANTMATERIET_MARKTACKE_PASSWORD")
    ),
    "TIMEOUT": float(os.environ.get("LANTMATERIET_ORTNAMN_TIMEOUT", "15")),
    "CACHE_SECONDS": int(
        os.environ.get("LANTMATERIET_ORTNAMN_CACHE_SECONDS", str(60 * 60 * 24 * 30))
    ),
}

# Byggnad Direkt (buildings) is a separate Lantmäteriet REST API, not OGC API
# Features - base path "distribution/produkter/byggnad/v3". Confirmed
# reachable at this BASE_URL (same "Missing Credentials" gateway error
# unauthenticated as Ortnamn above). Unlike Ortnamn, it accepts an arbitrary
# search geometry (POST /referens/geometri), but with a documented per-
# request limit (1,000,000 m² area, 200,000 m perimeter) - larger areas are
# tiled client-side, see tempus/services/lantmateriet.py. Falls back to the
# Marktäcke credentials above (same Geotorget account) unless its own are
# set - verify live whether this product needs its own API Portal
# subscription before assuming the shared credentials work here too.
LANTMATERIET_BYGGNAD = {
    "BASE_URL": os.environ.get(
        "LANTMATERIET_BYGGNAD_BASE_URL",
        "https://api.lantmateriet.se/distribution/produkter/byggnad/v3",
    ),
    "ACCESS_TOKEN": os.environ.get(
        "LANTMATERIET_BYGGNAD_ACCESS_TOKEN",
        os.environ.get("LANTMATERIET_MARKTACKE_ACCESS_TOKEN"),
    ),
    "USERNAME": os.environ.get(
        "LANTMATERIET_BYGGNAD_USERNAME", os.environ.get("LANTMATERIET_MARKTACKE_USERNAME")
    ),
    "PASSWORD": os.environ.get(
        "LANTMATERIET_BYGGNAD_PASSWORD", os.environ.get("LANTMATERIET_MARKTACKE_PASSWORD")
    ),
    "TIMEOUT": float(os.environ.get("LANTMATERIET_BYGGNAD_TIMEOUT", "15")),
    "CACHE_SECONDS": int(
        os.environ.get("LANTMATERIET_BYGGNAD_CACHE_SECONDS", str(60 * 60 * 24 * 30))
    ),
    "MAX_AREA_SQM": int(os.environ.get("LANTMATERIET_BYGGNAD_MAX_AREA_SQM", "1000000")),
    "MAX_PERIMETER_M": int(os.environ.get("LANTMATERIET_BYGGNAD_MAX_PERIMETER_M", "200000")),
    "MAX_TILES": int(os.environ.get("LANTMATERIET_BYGGNAD_MAX_TILES", "400")),
}

# Free, keyless OpenStreetMap vector tiles for the visual basemap. Tempus does
# not proxy these tiles; it only exposes this public style URL to its frontend.
TEMPUS_MAP_BASEMAP = {
    "provider": "OpenFreeMap",
    "style_url": os.environ.get(
        "TEMPUS_MAP_BASEMAP_STYLE_URL", "https://tiles.openfreemap.org/styles/liberty"
    ),
    "attribution": "",
    "initial_view": {"center": [15.0, 62.0], "zoom": 4.5},
}


# OpenStreetMap building footprints via the public Overpass API - replaces
# Lantmäteriet's Byggnad Direkt (needs a legal review) for the Locale layers.
# No key. Data is ODbL: credit "© OpenStreetMap contributors" where shown.
# See tempus/services/openstreetmap.py.
OVERPASS_API = {
    "URL": os.environ.get("OVERPASS_URL", "https://overpass-api.de/api/interpreter"),
    "USER_AGENT": os.environ.get("OVERPASS_USER_AGENT", "origo-tempus"),
    "TIMEOUT": int(os.environ.get("OVERPASS_TIMEOUT", "120")),
    "CACHE_SECONDS": int(os.environ.get("OVERPASS_CACHE_SECONDS", str(60 * 60 * 24 * 30))),
    "MAX_FEATURES": int(os.environ.get("OVERPASS_MAX_FEATURES", "30000")),
}

# Trafikverket's open API (NVDB roads). One XML-over-POST endpoint; the API key
# is sent inside the request body, so it has nothing to do with the Lantmäteriet
# credentials above. See tempus/services/trafikverket.py.
TRAFIKVERKET_API = {
    "TOKEN": os.environ.get("TRAFIKVERKET_TOKEN"),
    "URL": os.environ.get(
        "TRAFIKVERKET_URL", "https://api.trafikinfo.trafikverket.se/v2/data.json"
    ),
    "TIMEOUT": float(os.environ.get("TRAFIKVERKET_TIMEOUT", "30")),
    "CACHE_SECONDS": int(
        os.environ.get("TRAFIKVERKET_CACHE_SECONDS", str(60 * 60 * 24 * 30))
    ),
    "PAGE_SIZE": int(os.environ.get("TRAFIKVERKET_PAGE_SIZE", "1000")),
    "MAX_FEATURES": int(os.environ.get("TRAFIKVERKET_MAX_FEATURES", "20000")),
}
