"""
Django settings for origo project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import re
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file (repo root) into os.environ if present. Real values
# in the environment always take precedence, so deployed environments that set
# variables directly are unaffected. See .env.example for the supported keys.
try:
    from dotenv import load_dotenv
except ImportError:
    pass
else:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-h($p9)mrt^)&@r(3$6%ek5^pp11-3!)_(!36llfkk4g+=5%h_#',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ---------------------------------------------------------------------------
# Domains
# ---------------------------------------------------------------------------
# The whole host/CORS/CSRF configuration below is derived from this single
# list. To bring a new domain online, just add it to the DOMAINS env var
# (comma-separated) - nothing else in this file needs to change:
#
#     DOMAINS=origo.test,xn--fvitsko-exa.se,example.com
#
# Each domain is expected to serve:
#   - the API at   <API_SUBDOMAIN>.<domain>
#   - a frontend at <sub>.<domain>   for every sub in FRONTEND_SUBDOMAINS
#
# Punycode (xn--...) domains work here as-is; use the encoded form.

DOMAINS = [
    d.strip()
    for d in os.environ.get('DOMAINS', 'origo.test').split(',')
    if d.strip()
]

FRONTEND_SUBDOMAINS = [
    s.strip()
    for s in os.environ.get('FRONTEND_SUBDOMAINS', 'flux,verso,apsis').split(',')
    if s.strip()
]

API_SUBDOMAIN = os.environ.get('API_SUBDOMAIN', 'origo.api')

# Ports the Next.js frontends run on in local development (for CSRF only).
FRONTEND_DEV_PORTS = [
    p.strip()
    for p in os.environ.get('FRONTEND_DEV_PORTS', '3000').split(',')
    if p.strip()
]


def _frontend_origins(schemes=('https',), ports=(None,)):
    """Build <scheme>://<sub>.<domain>[:port] for every frontend subdomain."""
    origins = []
    for domain in DOMAINS:
        for sub in FRONTEND_SUBDOMAINS:
            for scheme in schemes:
                for port in ports:
                    host = f'{sub}.{domain}'
                    origins.append(
                        f'{scheme}://{host}:{port}' if port else f'{scheme}://{host}'
                    )
    return origins


# An explicit ALLOWED_HOSTS env var still wins; otherwise allow every domain
# and all of its subdomains.
if os.environ.get('ALLOWED_HOSTS'):
    ALLOWED_HOSTS = [h.strip() for h in os.environ['ALLOWED_HOSTS'].split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    for domain in DOMAINS:
        ALLOWED_HOSTS += [domain, f'.{domain}']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_tasks',
    'django_tasks_db',
    'corsheaders',
    'accounts',
    'flux',
    'verso',
    'apsis',
    'tempus'
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

ROOT_URLCONF = 'origo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'origo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# DATABASE_URL unset -> local SQLite. A PostgreSQL URL is parsed with the
# standard library so database configuration has no third-party dependency.

database_url = os.environ.get('DATABASE_URL')

if database_url:
    parsed_database_url = urlparse(database_url)
    if parsed_database_url.scheme not in ('postgres', 'postgresql'):
        raise ValueError('DATABASE_URL must use the postgres or postgresql scheme.')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote(parsed_database_url.path.lstrip('/')),
            'USER': unquote(parsed_database_url.username or ''),
            'PASSWORD': unquote(parsed_database_url.password or ''),
            'HOST': parsed_database_url.hostname or '',
            'PORT': parsed_database_url.port or '',
            # The threaded Django development server creates a new request
            # thread frequently; retaining a connection for ten minutes per
            # thread can exhaust a small remote PostgreSQL instance even for
            # one user. Keep local connections request-scoped, while allowing
            # production to opt into a bounded lifetime.
            'CONN_MAX_AGE': int(
                os.environ.get('DB_CONN_MAX_AGE', '0' if DEBUG else '60')
            ),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': dict(parse_qsl(parsed_database_url.query)),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}


# Background tasks (django-tasks / DEP 0014)
# Phenogram generation runs off the request cycle. The database backend
# (django-tasks-db) needs a worker process: `python manage.py db_worker`. Set
# TASKS_BACKEND to `django_tasks.backends.immediate.ImmediateBackend` to run
# tasks inline (dev, or a deploy with no worker); tests force the immediate
# backend.

TASKS = {
    'default': {
        'BACKEND': os.environ.get(
            'TASKS_BACKEND',
            'django_tasks_db.DatabaseBackend',
        ),
    }
}


# Cross-subdomain session cookie
# The Next.js frontends live on separate subdomains of a shared root domain
# and need to share the Django session cookie. A cookie can only be scoped to
# one root domain, so the session/CSRF cookies use ROOT_DOMAIN, which defaults
# to the first entry in DOMAINS. Override via the ROOT_DOMAIN env var if the
# primary domain is not listed first.

ROOT_DOMAIN = os.environ.get('ROOT_DOMAIN', DOMAINS[0])

SESSION_COOKIE_DOMAIN = f'.{ROOT_DOMAIN}'
CSRF_COOKIE_DOMAIN = f'.{ROOT_DOMAIN}'


# CORS
# https://github.com/adamchainz/django-cors-headers
# Allows the separately-hosted Next.js frontends to call this API with
# credentials (the session cookie) attached. Derived from DOMAINS; set the
# CORS_ALLOWED_ORIGINS env var to override completely.

if os.environ.get('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in os.environ['CORS_ALLOWED_ORIGINS'].split(',') if o.strip()
    ]
else:
    CORS_ALLOWED_ORIGINS = _frontend_origins(schemes=('https',))

    # Frontends are separated by subdomain. Trust any frontend subdomain below
    # a configured root domain so a new app does not also require a settings
    # change. DNS for these domains must therefore remain under our control.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        rf'^https://[a-z0-9-]+\.{re.escape(domain)}$'
        for domain in DOMAINS
    ] + [
        rf'^https?://[a-z0-9-]+\.{re.escape(domain)}:{re.escape(port)}$'
        for domain in DOMAINS
        for port in FRONTEND_DEV_PORTS
    ]

CORS_ALLOW_CREDENTIALS = True

if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in os.environ['CSRF_TRUSTED_ORIGINS'].split(',') if o.strip()
    ]
else:
    CSRF_TRUSTED_ORIGINS = (
        [f'https://{API_SUBDOMAIN}.{domain}' for domain in DOMAINS]
        + [f'https://*.{domain}' for domain in DOMAINS]
        + [
            f'{scheme}://*.{domain}:{port}'
            for domain in DOMAINS
            for scheme in ('http', 'https')
            for port in FRONTEND_DEV_PORTS
        ]
    )


# ---------------------------------------------------------------------------
# SLU Artdatabanken APIs (used by the tempus app)
# ---------------------------------------------------------------------------
# Species observations, Dyntaxa taxonomy and Artfakta species information, all
# behind one API gateway at api.artdatabanken.se. Each product has its own
# subscription key, issued on the developer portal (api-portal.artdatabanken.se).
# Calls are no-ops until the relevant *_KEY variable is set; see
# tempus/services/artdatabanken.py and .claude/skills/artdatabanken-api/.

ARTDATABANKEN = {
    'SPECIES_OBSERVATION_URL': os.environ.get(
        'ARTDATABANKEN_SPECIES_OBSERVATION_URL',
        'https://api.artdatabanken.se/species-observation-system/v1',
    ),
    'TAXON_SERVICE_URL': os.environ.get(
        'ARTDATABANKEN_TAXON_SERVICE_URL',
        'https://api.artdatabanken.se/taxonservice/v1',
    ),
    'SPECIES_INFORMATION_URL': os.environ.get(
        'ARTDATABANKEN_SPECIES_INFORMATION_URL',
        'https://api.artdatabanken.se/information/v1',
    ),
    'SUBSCRIPTION_KEY_SOS': os.environ.get('ARTDATABANKEN_SUBSCRIPTION_KEY_SOS'),
    'SUBSCRIPTION_KEY_TAXON': os.environ.get('ARTDATABANKEN_SUBSCRIPTION_KEY_TAXON'),
    'SUBSCRIPTION_KEY_SPECIES_INFORMATION': os.environ.get(
        'ARTDATABANKEN_SUBSCRIPTION_KEY_SPECIES_INFORMATION'
    ),
    'TIMEOUT': float(os.environ.get('ARTDATABANKEN_TIMEOUT', '30')),
    # SOS observation pages used to build phenograms are substantially larger
    # than taxonomy metadata responses and need a separate socket timeout.
    'PHENOGRAM_TIMEOUT': float(
        os.environ.get('ARTDATABANKEN_PHENOGRAM_TIMEOUT', '60')
    ),
    # Minimum quiet period after any Artdatabanken response before another
    # Dyntaxa, Artfakta or SOS request may start. Shared across local processes.
    'COOLDOWN_SECONDS': float(
        os.environ.get('ARTDATABANKEN_COOLDOWN_SECONDS', '1')
    ),
    'COOLDOWN_STATE_FILE': os.environ.get(
        'ARTDATABANKEN_COOLDOWN_STATE_FILE'
    ),
    'USER_AGENT': os.environ.get(
        'ARTDATABANKEN_USER_AGENT', 'Tempus (+tempus.services.artdatabanken)'
    ),
    # Artfakta SpeciesDataService dataset path segments. The biotoper segment is
    # unverified; override if biotopes come back empty (see BIOTOPES_DATASET in
    # tempus/services/artdatabanken.py).
    'SPECIESDATA_LANDSCAPES_PATH': os.environ.get(
        'ARTDATABANKEN_SPECIESDATA_LANDSCAPES_PATH', 'landscapetypes'
    ),
    'SPECIESDATA_BIOTOPES_PATH': os.environ.get(
        'ARTDATABANKEN_SPECIESDATA_BIOTOPES_PATH', 'biotopes'
    ),
}
