# Generated by Django 6.1 on 2026-09-20 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_version', 'target_version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LexicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=16)),
                ('part_of_speech', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('inflection_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['lemma', 'language', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=16)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['work', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TextUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('chapter', 'Chapter'), ('paragraph', 'Paragraph'), ('line', 'Line')], max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='opus.textunit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_units', to='opus.textversion')),
            ],
            options={
                'ordering': ['version', 'parent_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=20)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opus_annotations', to=settings.AUTH_USER_MODEL)),
                ('lexical_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='opus.lexicalentry')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='opus.textunit')),
            ],
            options={
                'ordering': ['unit', 'start_offset', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_start', models.CharField(blank=True, max_length=255, null=True)),
                ('source_end', models.CharField(blank=True, max_length=255, null=True)),
                ('target_start', models.CharField(blank=True, max_length=255, null=True)),
                ('target_end', models.CharField(blank=True, max_length=255, null=True)),
                ('alignment_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('partial', 'Partial'), ('omitted', 'Omitted'), ('inserted', 'Inserted'), ('uncertain', 'Uncertain')], max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alignment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='opus.alignmentset')),
                ('source_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_alignments', to='opus.textunit')),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_alignments', to='opus.textunit')),
            ],
            options={
                'ordering': ['alignment_set', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('file_type', models.CharField(max_length=50)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='opus.textversion')),
            ],
            options={
                'ordering': ['version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opus_reading_progress', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='opus.textunit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='opus.textversion')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('text_snapshot', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opus_excerpts', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='opus.textunit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='opus.textversion')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opus_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='opus.textunit')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='opus.textversion')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='alignmentset',
            name='source_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_alignment_sets', to='opus.textversion'),
        ),
        migrations.AddField(
            model_name='alignmentset',
            name='target_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_alignment_sets', to='opus.textversion'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opus_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='textversion',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='opus.work'),
        ),
        migrations.AddConstraint(
            model_name='textunit',
            constraint=models.UniqueConstraint(fields=('version', 'parent', 'position'), name='opus_textunit_unique_sibling_position'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='opus_reading_progress_per_user_version'),
        ),
    ]
