# Generated by Django 6.1 on 2026-09-21 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textversion',
            name='work',
        ),
        migrations.AlterModelOptions(
            name='alignmentset',
            options={'ordering': ['work', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='alignmentset',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alignmentset',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alignmentset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opus_alignment_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alignmentset',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alignment_sets', to='opus.work'),
        ),
        migrations.CreateModel(
            name='AlignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('alignment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='opus.alignmentset')),
            ],
            options={
                'ordering': ['alignment_set', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=16)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='opus.work')),
            ],
            options={
                'ordering': ['work', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlignmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('alignment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='opus.alignmentset')),
                ('text_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_versions', to='opus.edition')),
            ],
            options={
                'ordering': ['alignment_set', 'display_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='alignmentset',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_alignment_sets', to='opus.edition'),
        ),
        migrations.AlterField(
            model_name='alignmentset',
            name='target_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_alignment_sets', to='opus.edition'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='opus.edition'),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='opus.edition'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='opus.edition'),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='opus.edition'),
        ),
        migrations.AlterField(
            model_name='textunit',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_units', to='opus.edition'),
        ),
        migrations.CreateModel(
            name='AlignmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('omitted', 'Omitted'), ('uncertain', 'Uncertain')], default='present', max_length=20)),
                ('end_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_member_ends', to='opus.textunit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='opus.alignmentgroup')),
                ('start_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_member_starts', to='opus.textunit')),
                ('alignment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='opus.alignmentversion')),
            ],
            options={
                'ordering': ['group', 'alignment_version', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'alignment_version'), name='opus_alignment_member_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='alignmentversion',
            constraint=models.UniqueConstraint(fields=('alignment_set', 'text_version'), name='opus_alignment_version_unique'),
        ),
        migrations.DeleteModel(
            name='TextVersion',
        ),
    ]
