# Generated by Django 6.1 on 2026-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0002_remove_textversion_work_alter_alignmentset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='shelves',
            field=models.ManyToManyField(blank=True, related_name='works', to='opus.shelf'),
        ),
    ]
