# Generated by Django 6.1 on 2026-09-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0003_shelf_work_author_work_year_work_shelves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('born', models.CharField(blank=True, max_length=100)),
                ('died', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='author',
        ),
        migrations.CreateModel(
            name='BibliographyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('external_provider', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliography_entries', to='opus.author')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliography_entries', to='opus.work')),
            ],
            options={
                'ordering': ['author', 'sort_order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuthorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('is_preferred', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='opus.author')),
            ],
            options={
                'ordering': ['author', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('author', 'name', 'language'), name='opus_author_alias_unique')],
            },
        ),
        migrations.CreateModel(
            name='AuthorIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wikidata', 'Wikidata'), ('viaf', 'VIAF'), ('openlibrary', 'Open Library'), ('loc', 'Library of Congress')], max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='opus.author')),
            ],
            options={
                'ordering': ['author', 'provider', 'id'],
                'constraints': [models.UniqueConstraint(fields=('author', 'provider', 'external_id'), name='opus_author_identifier_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('commentator', 'Commentator')], default='author', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='opus.author')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='opus.work')),
            ],
            options={
                'ordering': ['work', 'display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('work', 'author', 'role'), name='opus_work_contributor_unique')],
            },
        ),
    ]
