# Generated by Django 6.1 on 2026-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '005_reading_state_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='target_kind',
            field=models.CharField(choices=[('word', 'Word'), ('phrase', 'Phrase'), ('unit', 'Whole text unit')], default='unit', max_length=20),
        ),
    ]
