# Generated by Django 6.1 on 2026-09-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0006_annotation_target_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('alignment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='opus.alignmentversion')),
                ('before_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_gaps', to='opus.textunit')),
            ],
            options={
                'ordering': ['alignment_version', 'before_unit', 'id'],
                'constraints': [models.UniqueConstraint(fields=('alignment_version', 'before_unit'), name='opus_alignment_gap_unique'), models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='opus_alignment_gap_count_positive')],
            },
        ),
        migrations.CreateModel(
            name='AlignmentSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='opus.alignmentversion')),
                ('end_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_span_ends', to='opus.textunit')),
                ('start_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_span_starts', to='opus.textunit')),
            ],
            options={
                'ordering': ['alignment_version', 'start_unit', 'id'],
                'constraints': [models.UniqueConstraint(fields=('alignment_version', 'start_unit'), name='opus_alignment_span_unique')],
            },
        ),
    ]
