# Generated by Django 6.1 on 2026-10-01 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0007_alignmentgap_alignmentspan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalentry',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lexicalentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opus_lexical_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entries', models.ManyToManyField(blank=True, related_name='glossaries', to='opus.lexicalentry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opus_glossaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'glossaries',
                'ordering': ['title', 'id'],
            },
        ),
    ]
