# Generated by Django 6.1 on 2026-10-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opus', '0008_lexicalentry_definition_lexicalentry_owner_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalentry',
            name='translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LexicalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('spelling', 'Spelling variant'), ('inflection', 'Inflected form')], default='spelling', max_length=20)),
                ('inflection', models.CharField(blank=True, max_length=255)),
                ('is_uncertain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='opus.lexicalentry')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lexical_forms', to='opus.textunit')),
            ],
            options={
                'ordering': ['entry', 'form', 'id'],
            },
        ),
    ]
